---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Linter

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  pull_request:
    branches: [ master ]

###############
# Set the Job #
###############
permissions:
  contents: read

jobs:
  linter:
    permissions:
      contents: read  # for actions/checkout to fetch code
      statuses: write  # for github/super-linter to mark status of each linter run
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@45fc0d88288beee4701c62761281edfee85655d7 # v5.0.0
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Markdown lint complains about the issue templates
          FILTER_REGEX_EXCLUDE: .github/ISSUE_TEMPLATE/*
          # TODO: Disable the perl linter as there are lots of errors that are not really understood, see https://github.com/adoptium/temurin-build/issues/2612
          VALIDATE_PERL: false
          # Disable google-java-format linter as it produces no useful error messages: see: https://github.com/adoptium/temurin-build/issues/3259
          VALIDATE_GOOGLE_JAVA_FORMAT: false
          # Disable cpplint, as not useful formatting
          VALIDATE_CPP: false

